/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.PersonProfile;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkAreaJPanel;

/**
 *
 * @author vedant
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory peopleDirectory;

    private PersonProfile p1;
    private PersonProfile p2;
    private PersonProfile p3;
    private PersonProfile p4;
    private PersonProfile p5;
    private PersonProfile p6;
    
    private Address hAdd1;
    private Address wAdd1;
    
    private Address hAdd2;
    private Address wAdd2;
    
    private Address hAdd3;
    private Address wAdd3;
    
    private Address hAdd4;
    private Address wAdd4;
    
    private Address hAdd5;
    private Address wAdd5;
    
    private Address hAdd6;
    private Address wAdd6;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        // Initialize a new Person Directory
        this.peopleDirectory = new PersonDirectory();
        
        // Add Person to the directory
        p1 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd1 = new Address();
        this.wAdd1 = new Address();
        
        // Add Person to the directory
        p2 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd2 = new Address();
        this.wAdd2 = new Address();
        
        // Add Person to the directory
        p3 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd3 = new Address();
        this.wAdd3 = new Address();
        
        // Add Person to the directory
        p4 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd4 = new Address();
        this.wAdd4 = new Address();

        // Add Person to the directory
        p5 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd5 = new Address();
        this.wAdd5 = new Address();
        
        // Add Person to the directory
        p6 = peopleDirectory.addPerson();
        // Add Addresses for Person 
        this.hAdd6 = new Address();
        this.wAdd6 = new Address();

        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        splitPane.setDividerLocation(80);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnPersonMng.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPersonMng.setText("Open Person Manager Work Area");
        btnPersonMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnPersonMng, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(541, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topJPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnPersonMng, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMngActionPerformed
        // TODO add your handling code here:

        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(userProcessContainer, peopleDirectory);
        userProcessContainer.add("AccountMngWorkAreaJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnPersonMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonMng;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        
        // Adding Person 1
        
        p1.setFirstName("Vedant");
        p1.setLastName("Mane");
        p1.setSSN(987654321);
        p1.setAge(25);
        
        hAdd1.setStreetAddress("30 South Huntington Avenue");
        hAdd1.setUnitNumber(3);
        hAdd1.setCity("Boston");
        hAdd1.setState("MA");
        hAdd1.setZipCode(02130);
        hAdd1.setPhoneNumber(1575655928);
        
        p1.setHomeAddress(hAdd1);

        wAdd1.setStreetAddress("360 Huntington Avenue");
        wAdd1.setUnitNumber(205);
        wAdd1.setCity("Boston");
        wAdd1.setState("MA");
        wAdd1.setZipCode(02115);
        wAdd1.setPhoneNumber(1293791098);

        p1.setWorkAddress(wAdd1);
        
        // Adding Person 2
        
        p2 = peopleDirectory.addPerson();
        p2.setFirstName("Aditya");
        p2.setLastName("Mitra");
        p2.setSSN(976798320);
        p2.setAge(24);
        
        hAdd2.setStreetAddress("890 Huntington Avenue");
        hAdd2.setUnitNumber(2);
        hAdd2.setCity("Boston");
        hAdd2.setState("MA");
        hAdd2.setZipCode(02115);
        hAdd2.setPhoneNumber(1579236052);

        p2.setHomeAddress(hAdd2);

        wAdd2.setStreetAddress("315 Beharkis Health Science Center");
        wAdd2.setUnitNumber(315);
        wAdd2.setCity("Boston");
        wAdd2.setState("MA");
        wAdd2.setZipCode(02115);
        wAdd2.setPhoneNumber(1923694690);

        p2.setWorkAddress(wAdd2);
        
        // Adding Person 3
        
        p3.setFirstName("Mansi");
        p3.setLastName("Kamble");
        p3.setSSN(692406249);
        p3.setAge(24);
        
        hAdd3.setStreetAddress("Harvard Square");
        hAdd3.setUnitNumber(7);
        hAdd3.setCity("Cambridge");
        hAdd3.setState("MA");
        hAdd3.setZipCode(02120);
        hAdd3.setPhoneNumber(1168310632);
        
        p3.setHomeAddress(hAdd3);

        wAdd3.setStreetAddress("203 Massachusetts Avenue");
        wAdd3.setUnitNumber(1);
        wAdd3.setCity("Boston");
        wAdd3.setState("MA");
        wAdd3.setZipCode(02110);
        wAdd3.setPhoneNumber(1782367936);

        p3.setWorkAddress(wAdd3);
        
        // Adding Person 4
        
        p4 = peopleDirectory.addPerson();
        p4.setFirstName("Bob");
        p4.setLastName("Marley");
        p4.setSSN(163802688);
        p4.setAge(54);
        
        hAdd4.setStreetAddress("100 Mozart Park");
        hAdd4.setUnitNumber(10);
        hAdd4.setCity("Jamaica Plain");
        hAdd4.setState("MA");
        hAdd4.setZipCode(02130);
        hAdd4.setPhoneNumber(1999900000);

        p4.setHomeAddress(hAdd4);

        wAdd4.setStreetAddress("101 Washinton Street");
        wAdd4.setUnitNumber(0);
        wAdd4.setCity("Quincy");
        wAdd4.setState("MA");
        wAdd4.setZipCode(98745);
        wAdd4.setPhoneNumber(1234567890);

        p4.setWorkAddress(wAdd4);
        
        // Adding Person 5
        
        p5.setFirstName("Taylor");
        p5.setLastName("Swift");
        p5.setSSN(923688263);
        p5.setAge(35);
        
        hAdd5.setStreetAddress("32 South Huntington");
        hAdd5.setUnitNumber(3);
        hAdd5.setCity("Boston");
        hAdd5.setState("MA");
        hAdd5.setZipCode(02140);
        hAdd5.setPhoneNumber(1575655929);
        
        p5.setHomeAddress(hAdd5);

        wAdd5.setStreetAddress("1989 Berkley Music School");
        wAdd5.setUnitNumber(22);
        wAdd5.setCity("Boston");
        wAdd5.setState("MA");
        wAdd5.setZipCode(02110);
        wAdd5.setPhoneNumber(1973828789);

        p5.setWorkAddress(wAdd5);
        
        // Adding Person 6
        
        p6 = peopleDirectory.addPerson();
        p6.setFirstName("Chris");
        p6.setLastName("Martin");
        p6.setSSN(638290172);
        p6.setAge(42);
        
        hAdd6.setStreetAddress("28 Huntington Avenue");
        hAdd6.setUnitNumber(1);
        hAdd6.setCity("Boston");
        hAdd6.setState("MA");
        hAdd6.setZipCode(02115);
        hAdd6.setPhoneNumber(1802338239);

        p6.setHomeAddress(hAdd6);

        wAdd6.setStreetAddress("315 Beharkis Health Science Center");
        wAdd6.setUnitNumber(315);
        wAdd6.setCity("Boston");
        wAdd6.setState("MA");
        wAdd6.setZipCode(02115);
        wAdd6.setPhoneNumber(1923694690);

        p6.setWorkAddress(wAdd6);
        
        
    }
}
